language: python
python:
  - "3.6"

sudo: required

env:
  CPLUS_INCLUDE_PATH=/usr/include/gdal
  C_INCLUDE_PATH=/usr/include/gdal

services:
  - docker

script:
 - pytest --cov=lostservice ./tests/test_*

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install pytest-cov

before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install -y gdal-bin libgdal-dev -y

after_success:
  - coverage report
  - docker build -t lostservice .
#  - docker login SpatialRouterRegistry.azurecr.io -u SpatialRouterRegistry -p "R09O8/N=6S8rsYW4poTHuM5Zz+ciHVc9"
#  - docker tag lostservice_img:latest SpatialRouterRegistry.azurecr.io/lostservice_img:latest
#  - docker push SpatialRouterRegistry.azurecr.io/lostservice_img
  - docker login -u AWS -p eyJwYXlsb2FkIjoiamRPclpDMmQrWXpLUmlDSGUxTzVPS1ZCWEkwRXZTWSs2clhQWFBpUUg2QzFPYWlBK2g0elA1WDdZK0NZUlh1QWNTVkFRTVBLZVRLT3ZvK3Zqc2lKV2p3R281K2hTbnVvdkdhZ3FnUy9Nc0Vkbkk3VXN0dWp4OTIyOVZJWFdoOHloM2kxU0wrUk9uZlZhV05HblliU0VUanhxSnlWcnVva3hWblZYL0EySmZjaUxmNEV1MjZRQ0U2aXdOUFBrZnlucEF6Wkg5ZUhiU1FpMGJrR2NEcUZBK3ZHOUdIUzhodkdTN0RXU1B5QllibnJmYndpVVlDVld3T3FETjdqOFR3OVp0MWlyM0k2K2dmNVh2TTFOVFN4UC9UMkt6T29TRlZzSDh1T3ZsSHR6emdvRGVMRTcvc0lTZldBdUE1OGg0N05zUVVVWnptRWFFSUMvU3dNTElzUkFWN3Zud0VQWkVJVWdiOUVwSnRwMHNBd2tGS3hFdVBaak5QaC9JaEloWDVzMGY3cHBnU2ZhbHMzMEFlVlRONXlGd2QwNE1JaXFROXVySndQSmNSVU9NZ2NsMW50V01nUjVCSzVRZGtFUjdqckI1a2tyNnNRR1FFRDRydHNLc2t4QklTMVF4WVZFaHltWW5HMStnTHEyTmRnYks0NUtEaG5keDZHdStaVjJscVV1RmRpZEFSeFhhVGx1aWFxeHBSTmgwZ3NyMWxTZVdrVVhlWHBzOTJiUHo5WnpuMWx5bDhnbFJWekhpQmhzZGpsZndUTHNwUm1ydXV1WTJiYm5nNEQ0RWV5RFVmT214cVkrQVhJbmdpWXNubjZSM2c5T2IxYjc2QTlrSWVpREpjMFh6VCt4UldoTDJMTjFLdWt5SVBoZGpPQnRlN2FTSkd1R2RPL1RQMnl2Z0hua0tsemcrWVRhVm9KZXlEamZMQTczYjc2Wk5IaWltazNZc2pNaWpPWXFORFZtWm4xOHg1bzdoYzlGV0ozNStnOVRwbVNMMHd0bFdWdVV3Ni94STdrcUhUdXUybjUxdmRyUmxNNldJcWxOejg4R3I5Qmovclh0NzBKbzZ3YmY5L3BEYWZpKzRDbFE0em9LTzlLWXBWeHRSZUFhOUUxM1doMXVJUFU0UTZWQW9BZWhuN0xTcDhQUUJQTUN5bGhqVWJvelp2cDNJelNtK1kyekVqcTB2eGFsUkgzYkx1ejMrZFVUcm1QRzlBZW9kTk96cWh6SzVyYkQrK3pFaHJYWWJ5cTJVSk80U0NIZ29JNEZ5Q1JOMDBJTkY4ZGJZbW1FMTJ3NW9XUFBzNW0yQ1k9IiwiZGF0YWtleSI6IkFRRUJBSGo2bGM0WElKdy83bG4wSGMwMERNZWs2R0V4SENiWTRSSXBUTUNJNThJblV3QUFBSDR3ZkFZSktvWklodmNOQVFjR29HOHdiUUlCQURCb0Jna3Foa2lHOXcwQkJ3RXdIZ1lKWUlaSUFXVURCQUV1TUJFRURMZDliU1hwTFVWK1dncU5iUUlCRUlBN2Q1QSt5UlBDYzZpaDlWQzdheEhwWWJPVTNjTGFUa3JScHdMeTUvRzY4YWsrbUo0Z1FkY2p0UWFJK3AwdmIzdjBMbUU1ZzRVRDlzOVZOd0U9IiwidmVyc2lvbiI6IjEiLCJ0eXBlIjoiREFUQV9LRVkifQ== https://709177336629.dkr.ecr.us-west-2.amazonaws.com
  - docker tag lostservice:latest 709177336629.dkr.ecr.us-west-2.amazonaws.com/lostservice:latest
  - docker push 709177336629.dkr.ecr.us-west-2.amazonaws.com/lostservice:latest

after_failure:

notifications:
  webhooks: https://outlook.office.com/webhook/8e85e59c-da42-4a8e-ad98-a7f0173b2a0e@ba05d72b-83fc-45fc-873b-b2841e0752de/TravisCI/a0a34daa96724c4cb6309283da957e6a/56b9b902-14c4-4a02-8944-45059ec4524c