language: python
python:
  - "3.6"

sudo: required

env:
  CPLUS_INCLUDE_PATH=/usr/include/gdal
  C_INCLUDE_PATH=/usr/include/gdal

services:
  - docker

script:
 - pytest --cov=lostservice ./tests/test_*

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install pytest-cov

before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install -y gdal-bin libgdal-dev -y

after_success:
  - coverage report
  - docker build -t lostservice_img .
  - docker login SpatialRouterRegistry.azurecr.io -u SpatialRouterRegistry -p "R09O8/N=6S8rsYW4poTHuM5Zz+ciHVc9"
  - docker tag lostservice_img SpatialRouterRegistry.azurecr.io/lostservice_img
  - docker push SpatialRouterRegistry.azurecr.io/lostservice_img

after_failure:

notifications:

webhooks: https://outlook.office.com/webhook/8e85e59c-da42-4a8e-ad98-a7f0173b2a0e@ba05d72b-83fc-45fc-873b-b2841e0752de/TravisCI/a0a34daa96724c4cb6309283da957e6a/56b9b902-14c4-4a02-8944-45059ec4524c