language: python
python:
- '3.6'
branches:
  only:
  - master
sudo: required
env:
  global:
  - CPLUS_INCLUDE_PATH=/usr/include/gdal
  - C_INCLUDE_PATH=/usr/include/gdal
  - AWS_DEFAULT_REGION=us-west-2
  - IMAGE_NAME=spatialrouter/lostservice
  - REMOTE_IMAGE_URL=709177336629.dkr.ecr.us-west-2.amazonaws.com/spatialrouter/lostservice
  - TASK_DEFINITION=spatialrouter-30-ci-task
  - SERVICE=spatialrouter-30-ci-service
  - CLUSTER=spatialrouter-30-ci-cluster
  - secure: AhL/tc4nUNXAOA8Ez4ecAToehf3B41wPVhDcWWJegchPPjQhkPcFVXiKZK4hjRujwHXYLavA1fR/Q8J7A3kPqvIuVXULaMdtukBSNdHD1uIHa7YfCe4M4j6P61MtLQV+4tbX7fWVacnKwib/7pAWgCXDVkum9D/EmYQar9efIZWV0p3phdX7PN55Aras6qriRQ4ZosWorL3FrQXiWgp8WBpLvIWNJ4CbTeCqJ9kX0zGDgNztoJ+yuijACTT0RuJPJJZfiLSN1VVjvciSrgile75GA7FWbb7Fh4AVfcAi+Bo8sRf+I+s8Rpi3ENdnV57kOQZ4xWi9HFRhCS5d9RycqZS2smL4OR8MySdWBxnAHAg5DuFEsGhXifZD5bKHWfcnN4XHAsDs/A8DpSbJd5QNIhvQJd3t+GISvSyxeM3htHHuV75iYMEOgANT441bo/ktmFc3EaYCIx0OFGLtDY2LfG4tu/iPxXyhsIhyLHLstL+X56W5Xw7rVRZPWdOs5/1D1UyvwhCHTKG1ZZtkaqUM1LwW7GA7tE4N3qdtdlFeRYmwFCELvlhR2gClq1Ue7AgP7k2js6wfFJOmrHvbB2kPRH23xRE2HlxaRZk/l328bikfDmSNLVAh9nUUnf+Z2lD9OYTtgrpiqigEAkMGUbaigBVhQ+BOECGtGx0+X3ffXXQ=
  - secure: FnwUZsrmckiacq6m7+hNeg1YzowOS6nEliNE4LuDBmeufMwk7/Sa+qHPclLYyS5xt6F3CU8IJS2MkbR8askw4jSGX/+F/z2Q1ES1KuU03+8xTRJ9X7PWMytDn4nqTiRADYphEar3u7Bz5Mm2F8SWIcmnxafjy6pgWZrRlZ6p5yjItXlSPgqN7UN//Nu8TO6lBVgANMBtJ4z3k8kg2FChThHk3BaVR0jG8h28EX8yTkA3+MqP6aYPK21PZZsOknEUvcXpDoZ3D54ME30dJWovc/uFjmR6A4BHfGN+SRJhzLR+l/+fUR9+Y4BM9FtbAQWh+YcfwS6/+RBWefnOiD3ql/a+jHL6lIKirdy2T+ixRvMDnHFTHLCGHkor0l1g7Kj09u23EGey5QCDjxm5jXzITG4t3WbHAtpFA0JpS32zI8qqcTOJ1nnRj9L9c/yHKro/iyhHMqsdzXR06cntQAKEeyGsGcPrk6/a9gL+jLQJ0wHQbRlBaUTCDLbq7pgtpV5THB0U0X3iIBOuYFgqcElo0il2BeCmM2O6U15HAeJ/5+38h+zXui0mM3PBrdQ+1kULTWOkBWOFA/5GK/kf1aHCmjow0h5BAX5ffvPldKjMWojmUamiIJDHCJQq6JosFmRwpJxlVuSzgTLgH59hVyusqYkejl1UOTF8mTqtbSRXCsc=
  - secure: QsikujjJfa2Y9yhCvPeT4peWQQNZZKHLCJKPQMiOqOylXCtR3wb1MGfXTXKnvUdp7mQ4mzmdLFmUfKJzVMiThxDp8vD1uH5GiNOlmSqQsXIOy51EdMP0LEqGoD3OL7p404f0CHBENiAvDA9cyOX1iscfbPFuJjHHqa6K4IgXaq16hT8s6wC2Eok37SXD6U7lz2XGBLtRWfkd6u7udehc4D9Hwk+atm0TIC88DFA50Z+lTACy825gN3lxgHkwjs1AZdkOBNfDmh2qaefjSPtrSI4szBOoOgDstVnAmsiFIpZS1QRIt4qcxF0J4hnSldY6zmIgWPtRkQ0wFGBwpq4yXDBSmRcW8U+EYFgi8pT8lUK6sqLZa+tK/uLbJcu1WzmuKKxWXds4vFxTdVr/MCFpMA04uQNB1iBcf/QCCPyRi73fHSXzrm3eCFwlA93G00B6JkUZEAO3vitgwBgrfP4pBeswK3mjezNgsei+Mo7oztprueEQQ0ltaFEgUPc4L/xRnUf6YWpL5JCO2Oi5gm5sZLSIZ0+MVhhR0PUALTesmlHIMUonvZMelGaYR5BellLj/PjBIhmjN1Ftk5k8MIskuiKhUMVY5vZ03+FqwkfLcU3CJ54hik6DYyUcmd7KG5FEqdHl+PHx8x0yA59spVYypP+AYGavOq1iLBZZonz76Cs=
services:
- docker
before_script:
- chmod +x ./lostservice_deploy.sh
- chmod +x ./run_newman_tests.sh
script:
- pytest --cov=lostservice ./tests/test_*
- ./lostservice_deploy.sh
install:
- pip install -r requirements.txt --extra-index-url $GEMFURY_URL
- pip install coverage
- pip install pytest-cov
- pip install awscli
- nvm install node 6.11.2
- npm install
before_install:
- sudo add-apt-repository -y ppa:ubuntugis/ppa -y
- sudo apt-get update -q
- sudo apt-get install -y gdal-bin libgdal-dev -y
- chmod +x ./ecs-deploy.sh
after_success:
- coverage report
notifications:
  webhooks: https://outlook.office.com/webhook/8e85e59c-da42-4a8e-ad98-a7f0173b2a0e@ba05d72b-83fc-45fc-873b-b2841e0752de/TravisCI/a0a34daa96724c4cb6309283da957e6a/56b9b902-14c4-4a02-8944-45059ec4524c
