language: python
python:
- '3.6'
branches:
  only:
  - master
sudo: required
env:
  global:
  - CPLUS_INCLUDE_PATH=/usr/include/gdal
  - C_INCLUDE_PATH=/usr/include/gdal
  - AWS_DEFAULT_REGION=us-west-2
  - IMAGE_NAME=spatialrouter/lostservice
  - REMOTE_IMAGE_URL=709177336629.dkr.ecr.us-west-2.amazonaws.com/spatialrouter/lostservice
  - TASK_DEFINITION=spatialrouter-30-ci-task
  - SERVICE=spatialrouter-30-ci-service
  - CLUSTER=spatialrouter-30-ci-cluster
  - secure: n58fyQidYAA4LkFrKlkJlt2kIdP1DMXoLdbNHDdD4PF6vxEl9edfXf/bWV/RF8GSETdTXwvFM2RexWRhA5ZCfxPwnh+ms6PfzXFOGuB+FtPP63gV1XYekTKA3YWigCzZibZBboBLrcd1d+8GeeM8DKuZcWiKwrJp0n+csowAL2C96q2K4TfNRAPjjt9ZAW15G/0uN8AitDEKl7BE0EiHMjcZOfFDbHcYF0hxWJaGfRcs2tyGw/KDDJhOCs6ebufHzbj9dBHTNC2LelLPZw6zx49kNp8sXLzowpkrumKpwA+84X8uvaoMi/Qnk+dHbFoIBbhKFEKjndN9cXP/tICiiiPxF7cw7QncOWQKDMU55NKfnlTlowe8iqjQlcy7TW5puBzMiispE5WLVvRsx+Ize/nJv8ILR9rQ9fB7dgF9WUx50ASB4hmhojRx94Vv+IwcAP/xFhuIdektncXYs9V6APjE8UquGEbi4vDQLzUEU2FM5sMNgLKORQGUxn8ydlqfF3MN1EkTrziEiL7RsBpL2wu/d6uEs2JSR/Gvp8CL2jrq54NG6PYsLJKthgeMFMjofu/qCOD8K68QwgOnvC289GFLSN6od3ZBs56Ug1+2D3QQaAvxuh/z07eWMLMWzYNbrQ8/Lu+piILiZqRDJNOtAsD3kF+inmK2jPVTrsjGG3I=
  - secure: QRR0Wx+xpE/AOcIjcFH0suj4XLrYIUGCcGl40xuk9nB8/j9p6J1ryCyXH4t5VbHl8hB46PvpHGEe/6sLoAC2rMfruy37oIXKSBNx3Hg44H415kktuzKPjceZ/YtZOaZVZaLqZqPG4Wb3WARwrtAWTyPr3qTCc8w2sD6Q/c/5AldOMSRtazNamerjZUaiXHvA5p6qzj74LAsn+4URnfM9wYv+1cbuKi0/OY9ph4OxalH25MgqRm+y7Ucq3Db0VlD7Ak32tTOgXYZtW0syKa0BpnJCj/h1VqHG09Pf+cSD5612hxIbQAo/I9fTiein4nKKCsttZeiTiEa4ZS4biYkEVW5NOs8ZruBDFy3G3TJqDSjLBnIxt1R6TQSob673AQgXUpntZME623kxrexLwV0D0c7tklkHCJRKfMRH1CxKVB5mwqsDKdRF5JkUDMVdBY3TK9E77tBhRaPztSi9N4Bt5fGF5M+GShn3RWrOFrJ1OSfM6TONeD3PGHUP6+DholCqTGNTqfHoVBUwTTExiJ+FW3PqFqXxl2wVmXXEhdnGSXnlrgv6kJiq64ogDyzBsGs+UEJCzkmU/jsxd22cuejZbqCswazQZc8foF/z6rGxsY0zz1PLSoC9/uI7s03SpDmB090BxTA7XgGI36DcLXf7MGaEXzA7Xs+uNaZdUzpj4Z0=
  - secure: TrK3CVKZVjHugh9+9DYKCyToPSneJxOR4fJBbHRx5RLkV5XVyo0X35UvINKRds9aEFHTZkZjmMVb2mff4G8RMl4iiI+c+IvD1C3fYvTtTzu6omDucv+RIATdGajZZCQ7ZhWz7dRM3ycuSvJm0coHNP82mOg1OSe8l8X42mbx5L4nRwMBLmC8/BGoMnQF/KU+IG0E+FuZKKP4oRzuQhGsdHmPeNKXX4tRxZDS16VMFmzfd0pPSbmoWcOleXOA8HEitnuZ5LTeQrf99ByZ9Qlujf8ZJMdthtKM5to6cbBd815o76Ipt9+yUsZMRsOKGipapTetBAniVKoey4Poq16B9ygRpaC/tia7u4Hm/IYkNtgnPEjU25RSziwzwmKdksFlpPbV6YQyWTuMnEkcwrrwnlcBhrB8UIIMe+NK7jOoZXFmu6arrJXMpzBwCgLnMKoONdsVXcxyAz90sNYxFAZERcR2NpotjooDVmTKotVnojqCE113DSudflES2mwtsRaFQlw1QruS+FR+SB0C5XCAR47hiBFt5TaIAqyRaWB9o0ctgLuhKqthC5EXu1fw5EFGmn/xugV6NFYZRj0DfqFz+io8ueeONVHT9fQH3qWSCgysyoXg1AYb6+31C4HMmbDV/IngeF6ADWoTu67Ym3pZjM+Mx17gd3a7bLjJuoyYU20=
services:
- docker
before_script:
- chmod +x ./lostservice_deploy.sh
- chmod +x ./run_newman_tests.sh
script:
- pytest --cov=lostservice ./tests/test_*
- ./lostservice_deploy.sh
install:
- pip install -r requirements.txt --extra-index-url $GEMFURY_URL
- pip install coverage
- pip install pytest-cov
- pip install awscli
- nvm install node 6.11.2
- npm install
before_install:
- sudo add-apt-repository -y ppa:ubuntugis/ppa -y
- sudo apt-get update -q
- sudo apt-get install -y gdal-bin libgdal-dev -y
- chmod +x ./ecs-deploy.sh
after_success:
- coverage report
notifications:
  webhooks: https://outlook.office.com/webhook/8e85e59c-da42-4a8e-ad98-a7f0173b2a0e@ba05d72b-83fc-45fc-873b-b2841e0752de/TravisCI/a0a34daa96724c4cb6309283da957e6a/56b9b902-14c4-4a02-8944-45059ec4524c
