language: python
python:
- '3.6'
branches:
  only:
  - master
sudo: required
env:
  global:
  - CPLUS_INCLUDE_PATH=/usr/include/gdal
  - C_INCLUDE_PATH=/usr/include/gdal
  - AWS_DEFAULT_REGION=us-west-2
  - IMAGE_NAME=spatialrouter/lostservice
  - REMOTE_IMAGE_URL=709177336629.dkr.ecr.us-west-2.amazonaws.com/spatialrouter/lostservice
  - TASK_DEFINITION=spatialrouter-30-ci-task
  - SERVICE=spatialrouter-30-ci-service
  - CLUSTER=spatialrouter-30-ci-cluster
  - secure: rtckTtQJS3sm1L9jPPgBmsGRYZDs+JOnvvdhceoZeVr43Ax163Pj3M4GUNaJs+q8ffWqoSKYMVcLWliFy8zIxKQkH5dv3No88qf5xfBd2R0bE0j9o9kHNWYZAtWtiY09GsOeWo2Fw/RdkR+/WtLXlFlvxQcWM9Vp1H/XD/TUObR79JpcFkupFVOUqZtfbDZK+05ZAtV8v3YfmCbNN8VZbPMXUMbNYYFyjibzZfiUzQWdNjolwcgOBIsS6oGPz7SHdpiYmJ4kLZjgQF18sGoH7CHi/UUz2ad7pWziDnSHiB3cPnixVma6e/Gmf8ivXt3YXS95X6qxZNUkDIOlQ/eqKDhngekFKqBL8iobkh898/waIy9Ns8KCZlpadsv0erEXUMzEGADqUZ8xJ46hTyO7KlumVp4XU33ZBdP8Q0ahxiIrvjRcaIdb6DYNqIEEmbzzS5uKtasN3UBWeiuXs0LdkX/Dqtob9AdJ6QOA0HGRFhPNd9zUGCL0YLBbKcRcm9Y7gbBjGlLAYWrQRgegQ4jkARGpaSkeRAwqbM3Go9vBxr0ZJSFWTYfeTdzrH3JBi0liS1bZ4JUcErBfGOcUbJny8TaidUJSD0KXujRzyDkfpEZJ9KBE6czf27amPSYHFDx8DE3T5J7ZyIcP4DY+SfdScXcYqyFh0Hwh7j0bYiOIDlA=
  - secure: BjiZLSPOFJm9oNenxjbiTEmDhcHp+z/bK1RlpmGTdRAn0FTYE9YQKBpQiREugFeiTtMDe59/m+snAfzWXTiEHiyO5Bx5EacrKEPKzVN8D/w31cqBQRHRJwW6byzx11XWeBO77jDrvo53NesruH2UUpG1R/NKRzHS7v8iQY77/A3FG8m8QhJucnaN8FOs4NuuqbWQSZY8pwENPYUW86gMhPl/KEH+1NbewVxXTND8JYgzGzdPWjuL2oltteorWUC/6oNiqjkgHmbTk7+gEX4q9BS2+sPDO9e6C4Z2wB2zPRAtnRSDt/LYV6gruj9U0q6ni+SeLqXN1O+CFdSYE2r7uQj60Q5MH1Sx2QcGeI86C0fR1DMBiY4Sis614+RgH5+cAVZPrC4x73HdGHShe9EiFn1okGH7PHPyT1SaWNst9ahbCGsvwbMvFkNColCrbuEc/Cq4VRE5GZ3Fr5TpYaEUFPSrFyFWeg59CF3nfdX3lW5j8YM4U0M6+UKTbtAoy/ySE2TxBVCM7FgK5C3ZgtIaQnFMOcgIE09WWVMbxD04pmGQPms6jzsWZqIaFZxUbXeXgEnYhtvMmMSqIrKZqPt0nZlUT4eOlZ3hbEl9C5zvOPoZ8LZlgUmm6+VtdHQkItcZ3seeeZw4odRHM5OCAOIT8Jb+9Im2tC3OPmEfXOxO7/g=
  - secure: Ggi5fRq1u4Sz1k56+NX1RexLaR5qqJtSDIegTpH/mb/jEpX/bPEN9MbdFjb/zTG+mPt7EnM+B5nWHJooDMFxhHGTnqbUIplRrqlcZOYzJQy52ugMtRjmaVQ05zckZ7sXM2szWmcU0uFDaOQ+sVSDiyQLqvUH2FFHjLhEmoWUTy4gqceK0nh7o4lRZabJ0ghQ9looq0elZzl7Yf4t3T/7bOerpsoO6tldNni5Jhx6mg2ntf4J6YaEeUP4MWvgAsEKr/XK04yZWYggmvVnMyP64Ht36GIHxDhV0MUIFXIf/FLg53aEHvprXK8r+D3QjdHs1+M/lfGTV1FUXkGfmSDwjC6AJ+lw3AZuxUCtP846gpTLA6v+3ozJcpXRCjjxIEVvknoKgT7AZb1/R5fDgaMFlxWxEsKWnUYgrSa/skBDFr662OysBqJsSTEM17NKL7cwLict295Bm1radZexfA3qma7uL4jV63GZkpH99IGyLVHD2ome9XaAETzjmVMCtr7s2wc5FMI3xya+qmDMs+Zi1++TduEmF2zdTOxMbZHAnTXmxxXxRT5CsT/0WCIwMDnKRMadvgBXWxLtOG03fmG9ItHPs5atnl4ljo33WgPSpYRG0Y0LbpcAGNPHFXLK4FcAPFkXij+uhOUxVBprCPsFaFhmhZ6rFmVCgNqcKamJbfw=
services:
- docker
before_script:
- chmod +x ./lostservice_deploy.sh
- chmod +x ./run_newman_tests.sh
script:
- pytest --cov=lostservice ./tests/test_*
- "./lostservice_deploy.sh"
install:
- pip install -r requirements.txt --extra-index-url $GEMFURY_URL
- pip install coverage
- pip install pytest-cov
- pip install awscli
- nvm install node 6.11.2
- npm install
before_install:
- sudo add-apt-repository -y ppa:ubuntugis/ppa -y
- sudo apt-get update -q
- sudo apt-get install -y gdal-bin libgdal-dev -y
- chmod +x ./ecs-deploy.sh
after_success:
- coverage report
notifications:
  webhooks: https://outlook.office.com/webhook/8e85e59c-da42-4a8e-ad98-a7f0173b2a0e@ba05d72b-83fc-45fc-873b-b2841e0752de/TravisCI/a0a34daa96724c4cb6309283da957e6a/56b9b902-14c4-4a02-8944-45059ec4524c
