language: python
python:
  - "3.6"

sudo: required

env:
  CPLUS_INCLUDE_PATH=/usr/include/gdal
  C_INCLUDE_PATH=/usr/include/gdal

services:
  - docker

script:
 - pytest --cov=lostservice ./tests/test_*

install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install pytest-cov

before_install:
  - sudo add-apt-repository -y ppa:ubuntugis/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install -y gdal-bin libgdal-dev -y

after_success:
  - coverage report
  - docker build -t lostservice_img .
#  - docker login SpatialRouterRegistry.azurecr.io -u SpatialRouterRegistry -p "R09O8/N=6S8rsYW4poTHuM5Zz+ciHVc9"
#  - docker tag lostservice_img:latest SpatialRouterRegistry.azurecr.io/lostservice_img:latest
#  - docker push SpatialRouterRegistry.azurecr.io/lostservice_img
  - docker login -u AWS -p eyJwYXlsb2FkIjoiWE5uazhRSlFjTkgwZEh4Rk8yTmlGdW13SVdHc0RwRmd3Uk5xNzE0QTFjVTZCNHRuejZBTXdXRUp1bW9jSmxUQXV0WDYrYjRubU5TK05samFTaWxSOGszNmVsakozNUU3N3RWWTFqQVhyYS94MHkwWW9wNHhZdTQyajZRZ0hWU0l3a1I3SUNtVU9JTUh2WEdNN2xDMEFMWXJsb1k4aUpDYU4vdkhiSHNJVXA2K2o0elhhcDlsZENORVJyUUdUR1Q4Z2gwUGIxVjNrNXk4SE5IOXVLd0hkT0RUSlJwdForZEZsS3dBN0kyQzN0dlc4SEtXUU9qbjBHYkZlOGZDWHY4R2pGTThXbHAxWnB6anFOSzA5cnROSG9IWk95cDdYOTNzUXhla3J6VkU4WFlxRm1WeDN4bzc3aXM0bFpaRDhSdmxhY1FLditlcG1qS1RRbnZpSm9EOWJvdUpWZnFhSWk1SjdEb1NWNG0vZmFYQWdGTHVrYXZFTVZxTTR6MlFWTFRYQ1haRWJYMG9LMXJodHFKcHp0ZDhUUG1KankxeEQvdmN6WEU0ZGRvWCtzdXo4UGdwOFV6Ly9udGVqMXJLVnFyVkhiZDRnbHJLRHZCNWNhSVkvN3B2WUdoVThRdHd6SHNnY2g3YVkvcklqZGQrQS9zUlJGRWpnU0toNzhtSTdvQjRMckY4T1VWNWx0RXArT2tJTHU2Qm9iZVU5Zy9BWXZSL0FESEZMUnJxTTJzbEdBbzgvK2JGSW4xZS9vckN3WVlOV0ZSaU43VWZxdDAyWmNsd2RCbzF0c0JVQStRU1J3aVlKNm1IRFBKS3Fuc2tZeTkwR2k4RkJsWDdZVWxaaWhnN2FYeTUwdmZ6TmlCKzl1cXFGSUQ3c1BYOEMwSFNMZ0JrZkJUK3ZOM2ZVa043T2FVUDF2U2NjRDcyUU0vaEFHeHFuOWZvUWdxamVQd0RKSVBsRjRQSWJHUFpSN3FtS3RDUGt3VUExME5ma0xIUGo2RmptY3JtbjBOMDg0aWlKNDl6RzhtL24zcGFDbWlrNmRCVVpYNy9xYzN4R1Q1alZiaHBJRVBsR213K0VlMkQ2SExreU5sdDljRWZab20yMmVzcTd4WFlZaUtHRTUvQkV5dEh1NzZ4U3VXWVhQTThzeHZLci9XZ2taU0Fxd2lLdnRjR2NhVUdQdUxwMEVUU21TWDRvM1NDT285N3VCNk9RalV6Vk1pdkoyWEErRjJVWUNQSWpqRmY5RTBaaHVlanFMelJTMnRrYWhnWnEyYkNvNzl5b2VhUDdhOEVSYndZbUpiSVRoYzNzanM9IiwiZGF0YWtleSI6IkFRRUJBSGo2bGM0WElKdy83bG4wSGMwMERNZWs2R0V4SENiWTRSSXBUTUNJNThJblV3QUFBSDR3ZkFZSktvWklodmNOQVFjR29HOHdiUUlCQURCb0Jna3Foa2lHOXcwQkJ3RXdIZ1lKWUlaSUFXVURCQUV1TUJFRURNZ3psK3NrbGRUeEl2UTBWQUlCRUlBN2hFOFBOcWVkNjEzNk1yWWcxTCtUN3BHaHRScVJWTUU3QkJ0aHRyVW9HQkRWV3FQY3NXQTJwSVFmZ2FPcUFVdXhFYU51cWh0bGE3K2xFRmM9IiwidmVyc2lvbiI6IjEiLCJ0eXBlIjoiREFUQV9LRVkifQ== https://709177336629.dkr.ecr.us-west-2.amazonaws.com
  - docker tag lostservice_img:latest 709177336629.dkr.ecr.us-west-2.amazonaws.com/lostservice_img:latest
  - docker push 709177336629.dkr.ecr.us-west-2.amazonaws.com/lostservice_img:latest

after_failure:

notifications:
  webhooks: https://outlook.office.com/webhook/8e85e59c-da42-4a8e-ad98-a7f0173b2a0e@ba05d72b-83fc-45fc-873b-b2841e0752de/TravisCI/a0a34daa96724c4cb6309283da957e6a/56b9b902-14c4-4a02-8944-45059ec4524c