version: '3.2'
services:
    portainer:
        image: portainer/portainer
        command: -H unix:///var/run/docker.sock
        ports:
          - 9000:9000
        volumes:
          - type: bind
            source: //var/run/docker.sock
            target: /var/run/docker.sock
        deploy:
          replicas: 1
          placement:
            constraints: [node.role == manager]
    nginx:
        image: nginx
        ports:
          - 80:80
        volumes:
          - type: bind
            source: ./nginx.conf
            target: /etc/nginx/nginx.conf
          #- type: bind
            # change this to point to the directory on the host where all certificates are placed
            #source: ./ssl
            #target: /etc/nginx/ssl
        deploy:
          placement:
            constraints: [node.role == manager]
        depends_on:
          - lostservice
    lostservice:
        image: 709177336629.dkr.ecr.us-west-2.amazonaws.com/spatialrouter/lostservice:latest
        environment:
            DBNAME: srgis
            DBUSER: postgres
            DBPASSWORD: GeoComm1
            DBHOSTNAME: pgpool
            DBPORT: 5432
            # this will always point to the directory specified as the target in the volume below.
            CONFIGFILE: /app/config/lostservice.ini
        ports:
            - 8080:8080
        volumes:
          - type: bind
            # change this to point to the directory on the host where lostservice.ini files live
            source: ./
            target: /app/config
        deploy:
          placement:
            constraints: [node.role == manager]
        depends_on:
            - pgpool
    pgmaster:
        image: 709177336629.dkr.ecr.us-west-2.amazonaws.com/geocomm/datadevil-postgres:latest
        environment:
            # Database configurations we want to use for container
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: GeoComm1
            REPLICATION_PASSWORD: GeoComm1  # default is replication_pass

            # defaults:            
            PARTNER_NODES: "pgmaster,pgslave1,pgslave2"
            NODE_ID: 1 # Integer number of node
            NODE_NAME: node1 # Node name
            CLUSTER_NODE_NETWORK_NAME: pgmaster # (default: hostname of the node)
            NODE_PRIORITY: 100  # (default: 100)
            CONFIGS: "search_path:'active,public'|listen_addresses:'*'"
            # in format variable1:value1[,variable2:value2[,...]]
            # used for pgpool.conf file

            CLUSTER_NAME: pg_cluster # default is pg_cluster
#           database we want to use for application
            POSTGRES_DB: srgis
            REPLICATION_DB: replication_db # default is replication_db
            REPLICATION_USER: replication # default is replication_user
        ports:
            - 5432:5432

    pgslave1:
        image: 709177336629.dkr.ecr.us-west-2.amazonaws.com/geocomm/datadevil-postgres:latest
        depends_on:
            - pgmaster
        environment:
            # Database configurations we want to use for container
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: GeoComm1
            REPLICATION_PASSWORD: GeoComm1 # default is replication_pass

            # defaults: 			
            PARTNER_NODES: "pgmaster,pgslave1,pgslave2"
            REPLICATION_PRIMARY_HOST: pgmaster
            NODE_ID: 2
            NODE_NAME: node2
            CLUSTER_NODE_NETWORK_NAME: pgslave1 # (default: hostname of the node)
#           database we want to use for application
            POSTGRES_DB: srgis
            REPLICATION_DB: replication_db # default is replication_db
            REPLICATION_USER: replication # default is replication_user
        ports:
            - 5441:5432

    pgslave2:
        image: 709177336629.dkr.ecr.us-west-2.amazonaws.com/geocomm/datadevil-postgres:latest
        depends_on:
            - pgmaster
        environment:
            # Database configurations we want to use for container
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: GeoComm1
            REPLICATION_PASSWORD: GeoComm1 # default is replication_pass

            # defaults: 
            PARTNER_NODES: "pgmaster,pgslave1,pgslave2"
            REPLICATION_PRIMARY_HOST: pgmaster
            NODE_ID: 3
            NODE_NAME: node3
            CLUSTER_NODE_NETWORK_NAME: pgslave2 # (default: hostname of the node)
            NODE_PRIORITY: 200  # (default: 100)
#           database we want to use for application
            POSTGRES_DB: srgis
            REPLICATION_DB: replication_db # default is replication_db
            REPLICATION_USER: replication # default is replication_user
        ports:
            - 5442:5432

    pgpool:
        image: 709177336629.dkr.ecr.us-west-2.amazonaws.com/geocomm/datadevil-pgpool:latest
        depends_on:
            - pgmaster
        environment:
            # configurations we want to use for container
            PCP_USER: postgres             # Needs to be the same as POSTGRES_USER
            PCP_PASSWORD: GeoComm1         # Needs to be the same as POSTGRES_PASSWORD 
            CHECK_PASSWORD: GeoComm1       # Needs to be the same as REPLICATION_PASSWORD
            DB_USERS: postgres:GeoComm1    # in format POSTGRES_USER:POSTGRES_PASSWORD
            BACKENDS: "0:pgmaster:5432:1:/var/lib/postgresql/data:ALLOW_TO_FAILOVER,1:pgslave1:5432:1:/var/lib/postgresql/data:ALLOW_TO_FAILOVER,2:pgslave2:5432:1:/var/lib/postgresql/data:ALLOW_TO_FAILOVER"
                      # in format num:host:port:weight:data_directory:flag[,...]
                      # defaults:
                      #   port: 5432
                      #   weight: 1
                      #   data_directory: /var/lib/postgresql/data
                      #   flag: ALLOW_TO_FAILOVER

            # defaults:			
            WAIT_BACKEND_TIMEOUT: 60
            CHECK_USER: replication
            CHECK_PGCONNECT_TIMEOUT: 3 #timout for checking if primary node is healthy
            REQUIRE_MIN_BACKENDS: 2 # minimal number of backends to start pgpool (some might be unreachable)
            CONFIGS: "num_init_children|250,max_pool|15"
                      # in format variable1|value1[,variable2|value2[,...]]
                      # used for pgpool.conf file
        ports:
            - 5430:5432
            - 9898:9898 # PCP

